# Generated by Django 5.1.1 on 2024-10-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_moodentry_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moodentry',
            old_name='feelings',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='moodentry',
            old_name='mood_intensity',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='moodentry',
            old_name='mood',
            new_name='Product',
        ),
    ]
